app_home_index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
app_home_tags_index:
    path:     /tags/index.html
    defaults: { _controller: AppBundle:Home:tags }
app_home_tags_delete:
    path: /tags/delete/{id}.html
    defaults: { _controller: AppBundle:Home:deletetag}
    requirements:
        id:  \d+
app_home_notif_ringtone:
    path:     /notif/ringtone.html
    defaults: { _controller: AppBundle:Home:notifRingtone }
app_home_notif_url:
    path:     /notif/url.html
    defaults: { _controller: AppBundle:Home:notifUrl }
app_home_notif_user:
    path:     /notif/user.html
    defaults: { _controller: AppBundle:Home:notifUser }
app_home_notif_category:
    path:     /notif/category.html
    defaults: { _controller: AppBundle:Home:notifCategory }
api_home_api_device:
    path:   /api/device/{tkn}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Home:api_device }
app_support_index:
    path:     /support/index.html
    defaults: { _controller: AppBundle:Support:index }
app_support_view:
    path:     /support/view/{id}.html
    defaults: { _controller: AppBundle:Support:view }
app_support_delete:
    path:     /support/delete/{id}.html
    defaults: { _controller: AppBundle:Support:delete }
api_support_add:
    path:     /api/support/add/{token}/{purchase}/
    defaults: { _controller: AppBundle:Support:api_add }
    methods: POST
#report
app_report_index:
    path:     /report/index.html
    defaults: { _controller: AppBundle:Report:index }
app_report_delete:
    path:     /report/delete/{id}.html
    defaults: { _controller: AppBundle:Report:delete }
api_report_add:
    path:     /api/report/add/{token}/{purchase}/
    defaults: { _controller: AppBundle:Report:api_add }
    methods: POST
#slide
app_slide_add:
    path: /slide/add.html
    defaults: { _controller: AppBundle:Slide:add}
app_slide_index:
    path: /slide/index.html
    defaults: { _controller: AppBundle:Slide:index}
app_slide_edit:
    path: /slide/{id}.html
    defaults: { _controller: AppBundle:Slide:edit}
    requirements:
        id:  \d+
app_slide_delete:
    path: /slide/delete/{id}.html
    defaults: { _controller: AppBundle:Slide:delete}
    requirements:
        id:  \d+
app_slide_up:
    path: /slide/up/{id}.html
    defaults: { _controller: AppBundle:Slide:up}
    requirements:
        id:  \d+
app_slide_down:
    path: /slide/down/{id}.html
    defaults: { _controller: AppBundle:Slide:down}
    requirements:
        id:  \d+
api_slide_all:
    path:     /api/slide/all/{token}/{purchase}/
    defaults: { _controller: AppBundle:Slide:api_all }
#category 
app_category_index:
    path: /category/index.html
    defaults: { _controller: AppBundle:Category:index}
app_category_add:
    path: /category/add.html
    defaults: { _controller: AppBundle:Category:add}
app_category_edit:
    path: /category/edit/{id}.html
    defaults: { _controller: AppBundle:Category:edit}
    requirements:
        id:  \d+
app_category_delete:
    path: /category/delete/{id}.html
    defaults: { _controller: AppBundle:Category:delete}
    requirements:
        id:  \d+
app_category_up:
    path: /category/up/{id}.html
    defaults: { _controller: AppBundle:Category:up}
    requirements:
        id:  \d+
app_category_down:
    path: /category/down/{id}.html
    defaults: { _controller: AppBundle:Category:down}
    requirements:
        id:  \d+
api_category_by:
    path:     /api/category/by/{id}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Category:api_by }
    requirements:
        id:  \d+  
api_category_all:
    path: /api/category/all/{token}/{purchase}/
    defaults: { _controller: AppBundle:Category:api_all}
api_category_popular:
    path: /api/category/popular/{token}/{purchase}/
    defaults: { _controller: AppBundle:Category:api_popular}
api_tags_all:
    path: /api/tags/all/{token}/{purchase}/
    defaults: { _controller: AppBundle:Category:api_tags}
#version
app_version_add:
    path: /version/add.html
    defaults: { _controller: AppBundle:Version:add}
app_version_index:
    path: /version/index.html
    defaults: { _controller: AppBundle:Version:index}
app_version_edit:
    path: /version/edit/{id}.html
    defaults: { _controller: AppBundle:Version:edit}
    requirements:
        id:  \d+
app_version_delete:
    path: /version/delete/{id}.html
    defaults: { _controller: AppBundle:Version:delete}
    requirements:
        id:  \d+
api_version_check:
    path: /api/version/check/{code}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Version:api_check_v2}
    requirements:
        code:  \d+

#wallpaper 
app_ringtone_share:
    path: /share/{id}.html
    defaults: { _controller: AppBundle:Ringtone:share}
    requirements:
        id:  \d+
app_ringtone_multi:
    path: /ringtone/multi.html
    defaults: { _controller: AppBundle:Ringtone:multi}
app_ringtone_add:
    path: /ringtone/add.html
    defaults: { _controller: AppBundle:Ringtone:add}
app_ringtone_reviews:
    path: /ringtone/reviews.html
    defaults: { _controller: AppBundle:Ringtone:reviews}
app_ringtone_index:
    path: /ringtone/index.html
    defaults: { _controller: AppBundle:Ringtone:index}
app_ringtone_edit:
    path: /ringtone/edit/{id}.html
    defaults: { _controller: AppBundle:Ringtone:edit}
    requirements:
        id:  \d+ 
app_ringtone_review:
    path: /ringtone/review/{id}.html
    defaults: { _controller: AppBundle:Ringtone:review}
    requirements:
        id:  \d+
app_ringtone_view:
    path: /ringtone/view/{id}.html
    defaults: { _controller: AppBundle:Ringtone:view}
    requirements:
        id:  \d+
app_ringtone_delete:
    path: /ringtone/delete/{id}.html
    defaults: { _controller: AppBundle:Ringtone:delete}
    requirements:
        id:  \d+
api_ringtone_all:
    path:     /api/ringtone/all/{order}/{page}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Ringtone:api_all }
    requirements:
        page: \d+
api_ringtone_by_category:
    path:     /api/ringtone/category/{page}/{category}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Ringtone:api_by_category }
    requirements:
        page: \d+
        category: \d+
api_ringtone_by_user:
    path:     /api/ringtone/user/{page}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Ringtone:api_by_user }
    requirements:
        page: \d+
        user: \d+
api_ringtone_get:
    path:     /api/ringtone/get/{id}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Ringtone:api_get }
    requirements:
        id: \d+
api_ringtone_by_me:
    path:     /api/ringtone/me/{page}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Ringtone:api_by_me }
    requirements:
        page: \d+
        user: \d+
api_ringtone_related:
    path:     /api/ringtone/related/{id}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Ringtone:api_related }
    requirements:
        id: \d+
api_ringtone_by_query:
    path:     /api/ringtone/query/{page}/{query}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Ringtone:api_by_query }
    requirements:
        page: \d+
api_ringtone_by_follow:
    path:     /api/ringtone/by/follow/{page}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Ringtone:api_by_follow }
    requirements:
        page: \d+
        user: \d+
api_rate_add:
    path:     /api/rate/add/{user}/{ringtone}/{value}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Ringtone:api_add_rate }
api_rate_get:
    path:     /api/rate/get/{user}/{ringtone}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Ringtone:api_get_rate }
api_ringtone_upload:
    path:     /api/ringtone/upload/{token}/{purchase}/
    defaults: { _controller: AppBundle:Ringtone:api_upload }
api_ringtone_add_download:
    path:     /api/ringtone/add/download/{token}/{purchase}/
    defaults: { _controller: AppBundle:Ringtone:api_add_download }
    methods: POST